# This is a basic workflow to help you get started with Actions

name: Main Pull Request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main, development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn

      - name: Lint App
        run: yarn lint

      - name: Build App
        run: yarn build

      - name: Styleling
        run: yarn stylelint
      - name: Telegram Notify Success
        uses: appleboy/telegram-action@master
        if: ${{ success() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ *The job has been completed.*
            #️⃣ Run # ${{github.run_number}}. Event type: *${{ github.event_name }}*
            🧑‍💻 Developer: *${{github.actor}}*
            🔗 Href: https://github.com/${{github.repository}}
          format: markdown
          disable_web_page_preview: "True"
      - name: Telegram Notify Failure
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ *The job has been failed!*
            #️⃣ Run # ${{github.run_number}}. Event type: *${{ github.event_name }}*
            🧑‍💻 Developer: *${{github.actor}}*
            🔗 Href: https://github.com/${{github.repository}}
          format: markdown
          disable_web_page_preview: "True"
